import './globals.css'

import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './components/theme/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'front-end',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR" suppressHydrationWarning className={inter.className}>
      <body className="bg-white dark:bg-black min-h-[100dvh]">
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  )
}
